### ISSUE TITLE
Disconnect.js fails and causes a server crash

### ISSUE THREAD

**Issue by dougperkes** [OfficeDev/Office-Add-in-Nodejs-ServerAuth#21]
Every time I try to use the disconnect functionality, I get a server crash. This stops the node.js server and I have to re-run `npm start` to get the sample running again. Here's the stack trace:

```
c:\dev\OfficeDev\Office-Add-in-NodeJS-ServerAuth\routes\disconnect.js:16
  for (var ii = 0; ii < user.providers.length; ii++) {
                            ^

TypeError: Cannot read property 'providers' of undefined
    at disconnectService (c:\dev\OfficeDev\Office-Add-in-NodeJS-ServerAuth\routes\disconnect.js:16:29)
    at c:\dev\OfficeDev\Office-Add-in-NodeJS-ServerAuth\routes\disconnect.js:81:23
    at c:\dev\OfficeDev\Office-Add-in-NodeJS-ServerAuth\db-helper.js:31:4
    at Request._callback (c:\dev\OfficeDev\Office-Add-in-NodeJS-ServerAuth\node_modules\nano\lib\nano.js:199:16)
    at self.callback (c:\dev\OfficeDev\Office-Add-in-NodeJS-ServerAuth\node_modules\nano\node_modules\request\request.js:198:22)
    at emitOne (events.js:77:13)
    at Request.emit (events.js:169:7)
    at Request.onRequestError (c:\dev\OfficeDev\Office-Add-in-NodeJS-ServerAuth\node_modules\nano\node_modules\request\request.js:820:8)
    at emitOne (events.js:77:13)
    at ClientRequest.emit (events.js:169:7)
```

**Comment by Ricalo** [comment]
Thanks, @dougperkes could you provide details about your environment?

- Operating System
- Browser or Office client used
- node and npm versions

It looks like the app can't retrieve the user from the database. I guess the database is running because you can sign in, but can't sign out. Just for the sake of getting things out of the way, could you check if your db is running right before hitting **disconnect**? You can check if db is up by going to [http://localhost:5984/_utils](http://localhost:5984/_utils).

I'll try to repro later today.

**Comment by dougperkes** [comment]
Good call on checking CouchDB. It turns out CouchDB wasn't started. It's curious that the Connect succeeded but the disconnect failed. Once I manually started it, the disconnect succeeded again. I should have thought to check that, but it wasn't apparent from the error.

Node: v4.2.4
OS: Win 10 Build 10586.63
Outlook 2016 Desktop: 16.0.6366.2062

**Comment by Ricalo** [comment]
Mmm... I'll keep an eye on this, seems like I should make the app fail earlier (or not start at all) if the DB is down. Also I should send an appropriate error message.

I'll close this issue and open another one to explicitly ask for the above changes.
